services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Monolit123
      - POSTGRES_DB=LovelyYou_test
    volumes:
      - postgres-db:/var/lib/postgresql/data
  api:
    build: .
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres-db: