services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Monolit123
      - POSTGRES_DB=LovelyYou_test
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: