services:
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/data/nginx.conf:/etc/nginx/conf.d/default.conf
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Monolit123
      - POSTGRES_DB=LovelyYou_test
    volumes:
      - postgres-db:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 6379:6379
  api:
    build: .
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  postgres-db: