name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-20.04
    steps:
      - name: Pull our code
        uses: actions/checkout@v4.1.1
      - name: Setup Python
        uses: actions/setup-python@v5.1.0
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install requirements.txt
        run: pip install -r requirements.txt