name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-20.04
    steps:
      - name: Pull our code
        uses: actions/checkout@v4.1.1
      - name: Say hi to pepsik
        run: echo "Hello, Pepsik"
