name: Build and Deploy Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  my_first_job:
	  runs-on: ubuntu-latest
	  steps:
      - name: My first step
        uses: actions/aws/ec2@main
